"""empty message

Revision ID: 1f8478204e4d
Revises: ad63d480470c
Create Date: 2021-04-22 19:26:03.003245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f8478204e4d'
down_revision = 'ad63d480470c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compra', 'id_estado')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compra', sa.Column('id_estado', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
