"""empty message

Revision ID: 3da954d9c733
Revises: 1f8478204e4d
Create Date: 2021-04-22 19:31:46.857746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3da954d9c733'
down_revision = '1f8478204e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalle_delivery_compra', 'id_compra',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'detalle_delivery_compra', 'compra', ['id_compra'], ['id_compra'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detalle_delivery_compra', type_='foreignkey')
    op.alter_column('detalle_delivery_compra', 'id_compra',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
