"""initial database migration

Revision ID: 5266458f0984
Revises: 
Create Date: 2021-04-22 19:22:24.189658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5266458f0984'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calificacion_producto',
    sa.Column('id_calificacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('puntuacion', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_calificacion')
    )
    op.create_table('categoria',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_table('compra',
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_vendedor', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('id_Estado_compra', sa.Integer(), nullable=True),
    sa.Column('id_Estado_pago', sa.Integer(), nullable=True),
    sa.Column('id_modalidad_entrega', sa.Integer(), nullable=True),
    sa.Column('descuento', sa.Float(), nullable=True),
    sa.Column('id_estado', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_compra')
    )
    op.create_table('detalle_delivery_compra',
    sa.Column('id_detalle_delivery', sa.Integer(), nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('direccion', sa.String(length=100), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('numero_contacto', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id_detalle_delivery')
    )
    op.create_table('estado',
    sa.Column('ID_ESTADO', sa.Integer(), nullable=False),
    sa.Column('NOMBRE', sa.String(length=45), nullable=True),
    sa.Column('DESCRIPCION', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('ID_ESTADO')
    )
    op.create_table('modalidad_entrega',
    sa.Column('id_modalidad_entrega', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_modalidad_entrega')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('vendedor',
    sa.Column('id_vendedor', sa.Integer(), nullable=False),
    sa.Column('paterno', sa.String(length=50), nullable=True),
    sa.Column('materno', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=10), nullable=True),
    sa.Column('dni', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id_vendedor')
    )
    op.create_table('producto',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('id_vendedor', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('imagen', sa.String(length=100), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('estado_activacion', sa.Integer(), nullable=True),
    sa.Column('fecha_adicion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_vendedor'], ['vendedor.id_vendedor'], ),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Integer(), nullable=False),
    sa.Column('contrasenia', sa.String(length=50), nullable=True),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=True),
    sa.Column('id_estado_actividad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('detalle_compra',
    sa.Column('id_detalle_compra', sa.Integer(), nullable=False),
    sa.Column('compra', sa.Integer(), nullable=False),
    sa.Column('producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('descuento', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['compra'], ['compra.id_compra'], ),
    sa.ForeignKeyConstraint(['producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_detalle_compra')
    )
    op.create_table('persona',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('apellido_paterno', sa.String(length=50), nullable=True),
    sa.Column('apellido_materno', sa.String(length=50), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('celular', sa.Integer(), nullable=True),
    sa.Column('genero', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_persona')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persona')
    op.drop_table('detalle_compra')
    op.drop_table('usuario')
    op.drop_table('producto')
    op.drop_table('vendedor')
    op.drop_table('rol')
    op.drop_table('modalidad_entrega')
    op.drop_table('estado')
    op.drop_table('detalle_delivery_compra')
    op.drop_table('compra')
    op.drop_table('cliente')
    op.drop_table('categoria')
    op.drop_table('calificacion_producto')
    # ### end Alembic commands ###
