"""empty message

Revision ID: 5e71d233389e
Revises: 3da954d9c733
Create Date: 2021-04-22 19:39:27.644786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e71d233389e'
down_revision = '3da954d9c733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compra', 'id_Estado_compra',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'compra', 'estado', ['id_Estado_compra'], ['ID_ESTADO'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'compra', type_='foreignkey')
    op.alter_column('compra', 'id_Estado_compra',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
