"""empty message

Revision ID: 6876fa66becc
Revises: 5e71d233389e
Create Date: 2021-04-22 19:40:46.881162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6876fa66becc'
down_revision = '5e71d233389e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compra', 'id_cliente',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'compra', 'cliente', ['id_cliente'], ['id_cliente'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'compra', type_='foreignkey')
    op.alter_column('compra', 'id_cliente',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
