"""empty message

Revision ID: 8164f17a6756
Revises: dfb36bc24b6c
Create Date: 2021-04-20 17:44:42.705783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8164f17a6756'
down_revision = 'dfb36bc24b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle_delivery_compra',
    sa.Column('id_detalle_delivery', sa.Integer(), nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('direccion', sa.String(length=100), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('numero_contacto', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id_detalle_delivery')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_delivery_compra')
    # ### end Alembic commands ###
