"""empty message

Revision ID: 827fbc1ea5d7
Revises: fe55f1b25c38
Create Date: 2021-04-19 23:47:00.297367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827fbc1ea5d7'
down_revision = 'fe55f1b25c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categoria')
    # ### end Alembic commands ###
