"""empty message

Revision ID: 9e115b4be3e3
Revises: 827fbc1ea5d7
Create Date: 2021-04-20 00:10:04.812564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e115b4be3e3'
down_revision = '827fbc1ea5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compra',
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_vendedor', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('id_Estado_compra', sa.Integer(), nullable=True),
    sa.Column('id_Estado_pago', sa.Integer(), nullable=True),
    sa.Column('id_modalidad_entrega', sa.Integer(), nullable=True),
    sa.Column('descuento', sa.Float(), nullable=True),
    sa.Column('id_estado', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_compra')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compra')
    # ### end Alembic commands ###
