"""empty message

Revision ID: 9e696462f299
Revises: d5e258f8df23
Create Date: 2021-04-21 12:18:43.426037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e696462f299'
down_revision = 'd5e258f8df23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modalidad_entrega', sa.Column('id_modalidad_entrega', sa.Integer(), nullable=False))
    op.drop_column('modalidad_entrega', 'Modalidad_Entrega')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modalidad_entrega', sa.Column('Modalidad_Entrega', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('modalidad_entrega', 'id_modalidad_entrega')
    # ### end Alembic commands ###
