"""empty message

Revision ID: f108d5517411
Revises: 6876fa66becc
Create Date: 2021-04-22 19:47:17.334372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f108d5517411'
down_revision = '6876fa66becc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compra', 'id_vendedor',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'compra', 'vendedor', ['id_vendedor'], ['id_vendedor'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'compra', type_='foreignkey')
    op.alter_column('compra', 'id_vendedor',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
